// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu1anBC5o1TX0B8WIxbZ57LfGpZQnzgnY',
    appId: '1:735018522693:web:c26bd738971ae986406b2c',
    messagingSenderId: '735018522693',
    projectId: 'market-59f63',
    authDomain: 'market-59f63.firebaseapp.com',
    storageBucket: 'market-59f63.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUbHW6huOHE95o6FazW1aKoQzKCpV6lLQ',
    appId: '1:735018522693:android:88c4ffbfaafdc96f406b2c',
    messagingSenderId: '735018522693',
    projectId: 'market-59f63',
    storageBucket: 'market-59f63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG7AeAnTEQp7cKmgAcMmSm3Fk9ju8FjLM',
    appId: '1:735018522693:ios:820c21261f8ae0bc406b2c',
    messagingSenderId: '735018522693',
    projectId: 'market-59f63',
    storageBucket: 'market-59f63.appspot.com',
    iosBundleId: 'com.example.market',
  );
}
